name: Adarsh Gupta
markdown: kramdown
keep_files: ["assets/css", "assets/js"] #Note that normally Jekyll destroys the destination folder before building, but now it leaves _site/assets/js and _site/assets/css untouched
exclude: ["node_modules", "gulpfile.js", "package.json", "assets/css", "assets/js"] # Config for Jekyll
